# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralLayout.setContentsMargins(15, 15, 15, 15)
        self.centralLayout.setSpacing(15)
        self.centralLayout.setObjectName("centralLayout")
        self.layoutRow1 = QtWidgets.QHBoxLayout()
        self.layoutRow1.setSpacing(10)
        self.layoutRow1.setObjectName("layoutRow1")
        self.slurButton = QtWidgets.QPushButton(self.centralwidget)
        self.slurButton.setCheckable(True)
        self.slurButton.setObjectName("slurButton")
        self.layoutRow1.addWidget(self.slurButton)
        self.unfoldingButton = QtWidgets.QPushButton(self.centralwidget)
        self.unfoldingButton.setCheckable(True)
        self.unfoldingButton.setObjectName("unfoldingButton")
        self.layoutRow1.addWidget(self.unfoldingButton)
        self.beamButton = QtWidgets.QPushButton(self.centralwidget)
        self.beamButton.setCheckable(True)
        self.beamButton.setObjectName("beamButton")
        self.layoutRow1.addWidget(self.beamButton)
        self.urlinieCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.urlinieCheckbox.setObjectName("urlinieCheckbox")
        self.layoutRow1.addWidget(self.urlinieCheckbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutRow1.addItem(spacerItem)
        self.keyLabel = QtWidgets.QLabel(self.centralwidget)
        self.keyLabel.setObjectName("keyLabel")
        self.layoutRow1.addWidget(self.keyLabel)
        self.keySelect = QtWidgets.QComboBox(self.centralwidget)
        self.keySelect.setObjectName("keySelect")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.layoutRow1.addWidget(self.keySelect)
        self.centralLayout.addLayout(self.layoutRow1)
        self.layoutRow2 = QtWidgets.QHBoxLayout()
        self.layoutRow2.setObjectName("layoutRow2")
        self.inputLabelVerticalLayout = QtWidgets.QVBoxLayout()
        self.inputLabelVerticalLayout.setObjectName("inputLabelVerticalLayout")
        self.measureLabel = QtWidgets.QLabel(self.centralwidget)
        self.measureLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.measureLabel.setObjectName("measureLabel")
        self.inputLabelVerticalLayout.addWidget(self.measureLabel)
        self.trebleLabel = QtWidgets.QLabel(self.centralwidget)
        self.trebleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trebleLabel.setObjectName("trebleLabel")
        self.inputLabelVerticalLayout.addWidget(self.trebleLabel)
        self.bassLabel = QtWidgets.QLabel(self.centralwidget)
        self.bassLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bassLabel.setObjectName("bassLabel")
        self.inputLabelVerticalLayout.addWidget(self.bassLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.inputLabelVerticalLayout.addItem(spacerItem1)
        self.layoutRow2.addLayout(self.inputLabelVerticalLayout)
        self.inputScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputScrollArea.sizePolicy().hasHeightForWidth())
        self.inputScrollArea.setSizePolicy(sizePolicy)
        self.inputScrollArea.setMinimumSize(QtCore.QSize(0, 156))
        self.inputScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inputScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.inputScrollArea.setWidgetResizable(True)
        self.inputScrollArea.setObjectName("inputScrollArea")
        self.inputScrollAreaWidget = QtWidgets.QWidget()
        self.inputScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 992, 140))
        self.inputScrollAreaWidget.setStyleSheet("QWidget {\n"
"background: white;\n"
"}")
        self.inputScrollAreaWidget.setObjectName("inputScrollAreaWidget")
        self.inputVerticalLayoutOuter = QtWidgets.QVBoxLayout(self.inputScrollAreaWidget)
        self.inputVerticalLayoutOuter.setContentsMargins(0, 0, 0, 0)
        self.inputVerticalLayoutOuter.setObjectName("inputVerticalLayoutOuter")
        self.inputVerticalLayout = QtWidgets.QVBoxLayout()
        self.inputVerticalLayout.setSpacing(0)
        self.inputVerticalLayout.setObjectName("inputVerticalLayout")
        self.measureInputWidget = QtWidgets.QWidget(self.inputScrollAreaWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureInputWidget.sizePolicy().hasHeightForWidth())
        self.measureInputWidget.setSizePolicy(sizePolicy)
        self.measureInputWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.measureInputWidget.setObjectName("measureInputWidget")
        self.measureInputWidgetOuter = QtWidgets.QHBoxLayout(self.measureInputWidget)
        self.measureInputWidgetOuter.setContentsMargins(0, 0, 0, 0)
        self.measureInputWidgetOuter.setObjectName("measureInputWidgetOuter")
        self.measureInputHLayout = QtWidgets.QHBoxLayout()
        self.measureInputHLayout.setContentsMargins(6, -1, -1, -1)
        self.measureInputHLayout.setObjectName("measureInputHLayout")
        self.measureInputWidgetOuter.addLayout(self.measureInputHLayout)
        self.inputVerticalLayout.addWidget(self.measureInputWidget)
        self.inputSeparator1 = QtWidgets.QFrame(self.inputScrollAreaWidget)
        self.inputSeparator1.setFrameShape(QtWidgets.QFrame.HLine)
        self.inputSeparator1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.inputSeparator1.setObjectName("inputSeparator1")
        self.inputVerticalLayout.addWidget(self.inputSeparator1)
        self.trebleInputWidget = QtWidgets.QWidget(self.inputScrollAreaWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trebleInputWidget.sizePolicy().hasHeightForWidth())
        self.trebleInputWidget.setSizePolicy(sizePolicy)
        self.trebleInputWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.trebleInputWidget.setObjectName("trebleInputWidget")
        self.trebleInputWidgetOuter = QtWidgets.QHBoxLayout(self.trebleInputWidget)
        self.trebleInputWidgetOuter.setContentsMargins(0, 0, 0, 0)
        self.trebleInputWidgetOuter.setObjectName("trebleInputWidgetOuter")
        self.trebleInputHLayout = QtWidgets.QHBoxLayout()
        self.trebleInputHLayout.setContentsMargins(6, -1, -1, -1)
        self.trebleInputHLayout.setObjectName("trebleInputHLayout")
        self.trebleInputWidgetOuter.addLayout(self.trebleInputHLayout)
        self.inputVerticalLayout.addWidget(self.trebleInputWidget)
        self.inputSeparator2 = QtWidgets.QFrame(self.inputScrollAreaWidget)
        self.inputSeparator2.setFrameShape(QtWidgets.QFrame.HLine)
        self.inputSeparator2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.inputSeparator2.setObjectName("inputSeparator2")
        self.inputVerticalLayout.addWidget(self.inputSeparator2)
        self.bassInputWidget = QtWidgets.QWidget(self.inputScrollAreaWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bassInputWidget.sizePolicy().hasHeightForWidth())
        self.bassInputWidget.setSizePolicy(sizePolicy)
        self.bassInputWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.bassInputWidget.setObjectName("bassInputWidget")
        self.bassInputWidgetOuter = QtWidgets.QHBoxLayout(self.bassInputWidget)
        self.bassInputWidgetOuter.setContentsMargins(0, 0, 0, 0)
        self.bassInputWidgetOuter.setObjectName("bassInputWidgetOuter")
        self.bassInputHLayout = QtWidgets.QHBoxLayout()
        self.bassInputHLayout.setContentsMargins(6, -1, -1, -1)
        self.bassInputHLayout.setObjectName("bassInputHLayout")
        self.bassInputWidgetOuter.addLayout(self.bassInputHLayout)
        self.inputVerticalLayout.addWidget(self.bassInputWidget)
        self.inputVerticalLayoutOuter.addLayout(self.inputVerticalLayout)
        self.inputScrollArea.setWidget(self.inputScrollAreaWidget)
        self.layoutRow2.addWidget(self.inputScrollArea)
        self.centralLayout.addLayout(self.layoutRow2)
        self.layoutRow3 = QtWidgets.QHBoxLayout()
        self.layoutRow3.setObjectName("layoutRow3")
        self.previewLabel = QtWidgets.QLabel(self.centralwidget)
        self.previewLabel.setObjectName("previewLabel")
        self.layoutRow3.addWidget(self.previewLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutRow3.addItem(spacerItem2)
        self.autoRefreshCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.autoRefreshCheckbox.setObjectName("autoRefreshCheckbox")
        self.layoutRow3.addWidget(self.autoRefreshCheckbox)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.layoutRow3.addWidget(self.refreshButton)
        self.centralLayout.addLayout(self.layoutRow3)
        self.layoutRow4 = QtWidgets.QHBoxLayout()
        self.layoutRow4.setObjectName("layoutRow4")
        self.previewScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.previewScrollArea.setWidgetResizable(True)
        self.previewScrollArea.setObjectName("previewScrollArea")
        self.previewScrollAreaWidget = QtWidgets.QWidget()
        self.previewScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 1030, 365))
        self.previewScrollAreaWidget.setObjectName("previewScrollAreaWidget")
        self.previewScrollAreaWidgetOuter = QtWidgets.QHBoxLayout(self.previewScrollAreaWidget)
        self.previewScrollAreaWidgetOuter.setObjectName("previewScrollAreaWidgetOuter")
        self.previewScrollArea.setWidget(self.previewScrollAreaWidget)
        self.layoutRow4.addWidget(self.previewScrollArea)
        self.zoomVLayout = QtWidgets.QVBoxLayout()
        self.zoomVLayout.setSpacing(5)
        self.zoomVLayout.setObjectName("zoomVLayout")
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomInButton.sizePolicy().hasHeightForWidth())
        self.zoomInButton.setSizePolicy(sizePolicy)
        self.zoomInButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.zoomInButton.setObjectName("zoomInButton")
        self.zoomVLayout.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.zoomVLayout.addWidget(self.zoomOutButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.zoomVLayout.addItem(spacerItem3)
        self.layoutRow4.addLayout(self.zoomVLayout)
        self.centralLayout.addLayout(self.layoutRow4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.propertiesPanel = QtWidgets.QDockWidget(MainWindow)
        self.propertiesPanel.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.propertiesPanel.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.propertiesPanel.setObjectName("propertiesPanel")
        self.propertiesPanelWidget = QtWidgets.QWidget()
        self.propertiesPanelWidget.setObjectName("propertiesPanelWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.propertiesPanelWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputPropertiesTabWidget = QtWidgets.QTabWidget(self.propertiesPanelWidget)
        self.inputPropertiesTabWidget.setObjectName("inputPropertiesTabWidget")
        self.noteTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteTab.sizePolicy().hasHeightForWidth())
        self.noteTab.setSizePolicy(sizePolicy)
        self.noteTab.setObjectName("noteTab")
        self.noteTabVerticalLayout = QtWidgets.QVBoxLayout(self.noteTab)
        self.noteTabVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.noteTabVerticalLayout.setObjectName("noteTabVerticalLayout")
        self.notePropertiesTree = QtWidgets.QTreeWidget(self.noteTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notePropertiesTree.sizePolicy().hasHeightForWidth())
        self.notePropertiesTree.setSizePolicy(sizePolicy)
        self.notePropertiesTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.notePropertiesTree.setAlternatingRowColors(True)
        self.notePropertiesTree.setWordWrap(True)
        self.notePropertiesTree.setObjectName("notePropertiesTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.notePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.notePropertiesTree.header().setDefaultSectionSize(125)
        self.noteTabVerticalLayout.addWidget(self.notePropertiesTree)
        self.inputPropertiesTabWidget.addTab(self.noteTab, "")
        self.measureTab = QtWidgets.QWidget()
        self.measureTab.setObjectName("measureTab")
        self.measureTabVerticalLayout = QtWidgets.QVBoxLayout(self.measureTab)
        self.measureTabVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.measureTabVerticalLayout.setObjectName("measureTabVerticalLayout")
        self.measurePropertiesTree = QtWidgets.QTreeWidget(self.measureTab)
        self.measurePropertiesTree.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.measurePropertiesTree.setAlternatingRowColors(True)
        self.measurePropertiesTree.setWordWrap(True)
        self.measurePropertiesTree.setObjectName("measurePropertiesTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.measurePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.measurePropertiesTree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.measurePropertiesTree.header().setDefaultSectionSize(150)
        self.measureTabVerticalLayout.addWidget(self.measurePropertiesTree)
        self.inputPropertiesTabWidget.addTab(self.measureTab, "")
        self.verticalLayout_2.addWidget(self.inputPropertiesTabWidget)
        self.elementPropertiesTabWidget = QtWidgets.QTabWidget(self.propertiesPanelWidget)
        self.elementPropertiesTabWidget.setObjectName("elementPropertiesTabWidget")
        self.slurTab = QtWidgets.QWidget()
        self.slurTab.setObjectName("slurTab")
        self.slurTabVerticalLayout = QtWidgets.QVBoxLayout(self.slurTab)
        self.slurTabVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.slurTabVerticalLayout.setObjectName("slurTabVerticalLayout")
        self.slurPropertiesTree = QtWidgets.QTreeWidget(self.slurTab)
        self.slurPropertiesTree.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.slurPropertiesTree.setAlternatingRowColors(True)
        self.slurPropertiesTree.setObjectName("slurPropertiesTree")
        self.slurTabVerticalLayout.addWidget(self.slurPropertiesTree)
        self.elementPropertiesTabWidget.addTab(self.slurTab, "")
        self.unfoldingTab = QtWidgets.QWidget()
        self.unfoldingTab.setObjectName("unfoldingTab")
        self.unfoldingTabVerticalLayout = QtWidgets.QVBoxLayout(self.unfoldingTab)
        self.unfoldingTabVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.unfoldingTabVerticalLayout.setObjectName("unfoldingTabVerticalLayout")
        self.unfoldingPropertiesTree = QtWidgets.QTreeWidget(self.unfoldingTab)
        self.unfoldingPropertiesTree.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.unfoldingPropertiesTree.setAlternatingRowColors(True)
        self.unfoldingPropertiesTree.setObjectName("unfoldingPropertiesTree")
        self.unfoldingTabVerticalLayout.addWidget(self.unfoldingPropertiesTree)
        self.elementPropertiesTabWidget.addTab(self.unfoldingTab, "")
        self.beamTab = QtWidgets.QWidget()
        self.beamTab.setObjectName("beamTab")
        self.beamTabVerticalLayout = QtWidgets.QVBoxLayout(self.beamTab)
        self.beamTabVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.beamTabVerticalLayout.setObjectName("beamTabVerticalLayout")
        self.beamPropertiesTree = QtWidgets.QTreeWidget(self.beamTab)
        self.beamPropertiesTree.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.beamPropertiesTree.setAlternatingRowColors(True)
        self.beamPropertiesTree.setObjectName("beamPropertiesTree")
        self.beamTabVerticalLayout.addWidget(self.beamPropertiesTree)
        self.elementPropertiesTabWidget.addTab(self.beamTab, "")
        self.verticalLayout_2.addWidget(self.elementPropertiesTabWidget)
        self.propertiesPanel.setWidget(self.propertiesPanelWidget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.propertiesPanel)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpn = QtWidgets.QAction(MainWindow)
        self.actionOpn.setObjectName("actionOpn")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionTogglePropertiesPanel = QtWidgets.QAction(MainWindow)
        self.actionTogglePropertiesPanel.setObjectName("actionTogglePropertiesPanel")
        self.actionRefreshPreview = QtWidgets.QAction(MainWindow)
        self.actionRefreshPreview.setObjectName("actionRefreshPreview")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExport_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionExport_as_PDF.setObjectName("actionExport_as_PDF")
        self.menuExport.addAction(self.actionExport_as_PDF)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpn)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuView.addAction(self.actionTogglePropertiesPanel)
        self.menuView.addAction(self.actionRefreshPreview)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.inputPropertiesTabWidget.setCurrentIndex(0)
        self.elementPropertiesTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.slurButton.setStatusTip(_translate("MainWindow", "Select this button then click two notes to form a slur"))
        self.slurButton.setText(_translate("MainWindow", "Slur"))
        self.unfoldingButton.setStatusTip(_translate("MainWindow", "Select this button then click two notes to form an unfolding"))
        self.unfoldingButton.setText(_translate("MainWindow", "Unfolding"))
        self.beamButton.setStatusTip(_translate("MainWindow", "Select this button then click a sequence of notes to form a beam"))
        self.beamButton.setText(_translate("MainWindow", "Beam"))
        self.urlinieCheckbox.setStatusTip(_translate("MainWindow", "Check to create an Urlinie"))
        self.urlinieCheckbox.setText(_translate("MainWindow", "Urlinie"))
        self.keyLabel.setText(_translate("MainWindow", "Key signature:"))
        self.keySelect.setStatusTip(_translate("MainWindow", "Pick a global key signature"))
        self.keySelect.setItemText(0, _translate("MainWindow", "C major"))
        self.keySelect.setItemText(1, _translate("MainWindow", "G major"))
        self.keySelect.setItemText(2, _translate("MainWindow", "D major"))
        self.keySelect.setItemText(3, _translate("MainWindow", "A major"))
        self.keySelect.setItemText(4, _translate("MainWindow", "E major"))
        self.keySelect.setItemText(5, _translate("MainWindow", "B major"))
        self.keySelect.setItemText(6, _translate("MainWindow", "F# major"))
        self.keySelect.setItemText(7, _translate("MainWindow", "C# major"))
        self.keySelect.setItemText(8, _translate("MainWindow", "Cb major"))
        self.keySelect.setItemText(9, _translate("MainWindow", "Gb major"))
        self.keySelect.setItemText(10, _translate("MainWindow", "Db major"))
        self.keySelect.setItemText(11, _translate("MainWindow", "Ab major"))
        self.keySelect.setItemText(12, _translate("MainWindow", "Eb major"))
        self.keySelect.setItemText(13, _translate("MainWindow", "Bb major"))
        self.keySelect.setItemText(14, _translate("MainWindow", "F major"))
        self.keySelect.setItemText(15, _translate("MainWindow", "A minor"))
        self.keySelect.setItemText(16, _translate("MainWindow", "E minor"))
        self.keySelect.setItemText(17, _translate("MainWindow", "B minor"))
        self.keySelect.setItemText(18, _translate("MainWindow", "F# minor"))
        self.keySelect.setItemText(19, _translate("MainWindow", "C# minor"))
        self.keySelect.setItemText(20, _translate("MainWindow", "G# minor"))
        self.keySelect.setItemText(21, _translate("MainWindow", "D# minor"))
        self.keySelect.setItemText(22, _translate("MainWindow", "A# minor"))
        self.keySelect.setItemText(23, _translate("MainWindow", "Ab minor"))
        self.keySelect.setItemText(24, _translate("MainWindow", "Eb minor"))
        self.keySelect.setItemText(25, _translate("MainWindow", "Bb minor"))
        self.keySelect.setItemText(26, _translate("MainWindow", "F minor"))
        self.keySelect.setItemText(27, _translate("MainWindow", "C minor"))
        self.keySelect.setItemText(28, _translate("MainWindow", "G minor"))
        self.keySelect.setItemText(29, _translate("MainWindow", "D minor"))
        self.measureLabel.setText(_translate("MainWindow", "Measure:"))
        self.trebleLabel.setText(_translate("MainWindow", "Treble:"))
        self.bassLabel.setText(_translate("MainWindow", "Bass:"))
        self.inputScrollArea.setStatusTip(_translate("MainWindow", "Add or remove notes"))
        self.previewLabel.setText(_translate("MainWindow", "Preview:"))
        self.autoRefreshCheckbox.setStatusTip(_translate("MainWindow", "Auto-refresh Schenkerian graph (uncheck for better performance)"))
        self.autoRefreshCheckbox.setText(_translate("MainWindow", "Auto-refresh"))
        self.refreshButton.setStatusTip(_translate("MainWindow", "Refresh Schenkerian graph"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.previewScrollArea.setStatusTip(_translate("MainWindow", "Schenkerian graph preview"))
        self.zoomInButton.setStatusTip(_translate("MainWindow", "Zoom in"))
        self.zoomInButton.setText(_translate("MainWindow", "+"))
        self.zoomOutButton.setStatusTip(_translate("MainWindow", "Zoom out"))
        self.zoomOutButton.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.propertiesPanel.setStatusTip(_translate("MainWindow", "Properties panel (Double click or press Ctrl + Q to toggle)"))
        self.propertiesPanel.setWindowTitle(_translate("MainWindow", "Properties"))
        self.notePropertiesTree.headerItem().setText(0, _translate("MainWindow", "Property"))
        self.notePropertiesTree.headerItem().setText(1, _translate("MainWindow", "Value"))
        __sortingEnabled = self.notePropertiesTree.isSortingEnabled()
        self.notePropertiesTree.setSortingEnabled(False)
        self.notePropertiesTree.topLevelItem(0).setText(0, _translate("MainWindow", "ID"))
        self.notePropertiesTree.topLevelItem(1).setText(0, _translate("MainWindow", "Note name"))
        self.notePropertiesTree.topLevelItem(2).setText(0, _translate("MainWindow", "Accidental"))
        self.notePropertiesTree.topLevelItem(3).setText(0, _translate("MainWindow", "Register"))
        self.notePropertiesTree.topLevelItem(4).setText(0, _translate("MainWindow", "Slurs with..."))
        self.notePropertiesTree.topLevelItem(5).setText(0, _translate("MainWindow", "Unfolds with..."))
        self.notePropertiesTree.topLevelItem(6).setText(0, _translate("MainWindow", "Beams with..."))
        self.notePropertiesTree.setSortingEnabled(__sortingEnabled)
        self.inputPropertiesTabWidget.setTabText(self.inputPropertiesTabWidget.indexOf(self.noteTab), _translate("MainWindow", "Note"))
        self.measurePropertiesTree.headerItem().setText(0, _translate("MainWindow", "Property"))
        self.measurePropertiesTree.headerItem().setText(1, _translate("MainWindow", "Value"))
        __sortingEnabled = self.measurePropertiesTree.isSortingEnabled()
        self.measurePropertiesTree.setSortingEnabled(False)
        self.measurePropertiesTree.topLevelItem(0).setText(0, _translate("MainWindow", "ID"))
        self.measurePropertiesTree.topLevelItem(1).setText(0, _translate("MainWindow", "Measure number"))
        self.measurePropertiesTree.setSortingEnabled(__sortingEnabled)
        self.inputPropertiesTabWidget.setTabText(self.inputPropertiesTabWidget.indexOf(self.measureTab), _translate("MainWindow", "Measure"))
        self.slurPropertiesTree.headerItem().setText(0, _translate("MainWindow", "Slur"))
        self.slurPropertiesTree.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.elementPropertiesTabWidget.setTabText(self.elementPropertiesTabWidget.indexOf(self.slurTab), _translate("MainWindow", "Slur"))
        self.unfoldingPropertiesTree.headerItem().setText(0, _translate("MainWindow", "Unfolding"))
        self.unfoldingPropertiesTree.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.elementPropertiesTabWidget.setTabText(self.elementPropertiesTabWidget.indexOf(self.unfoldingTab), _translate("MainWindow", "Unfolding"))
        self.beamPropertiesTree.headerItem().setText(0, _translate("MainWindow", "Beam"))
        self.beamPropertiesTree.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.elementPropertiesTabWidget.setTabText(self.elementPropertiesTabWidget.indexOf(self.beamTab), _translate("MainWindow", "Beam"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpn.setText(_translate("MainWindow", "Open"))
        self.actionOpn.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionTogglePropertiesPanel.setText(_translate("MainWindow", "Toggle properties panel"))
        self.actionTogglePropertiesPanel.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionRefreshPreview.setText(_translate("MainWindow", "Refresh preview"))
        self.actionRefreshPreview.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As..."))
        self.actionExport_as_PDF.setText(_translate("MainWindow", "Export as PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
