# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Schenky(object):
    def setupUi(self, Schenky):
        Schenky.setObjectName("Schenky")
        Schenky.resize(1088, 614)
        Schenky.setMinimumSize(QtCore.QSize(1088, 614))
        Schenky.setMaximumSize(QtCore.QSize(1088, 614))
        self.centralwidget = QtWidgets.QWidget(Schenky)
        self.centralwidget.setObjectName("centralwidget")
        self.keyLabel = QtWidgets.QLabel(self.centralwidget)
        self.keyLabel.setGeometry(QtCore.QRect(30, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.keyLabel.setFont(font)
        self.keyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyLabel.setObjectName("keyLabel")
        self.keySelect = QtWidgets.QComboBox(self.centralwidget)
        self.keySelect.setGeometry(QtCore.QRect(142, 20, 111, 31))
        self.keySelect.setObjectName("keySelect")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.keySelect.addItem("")
        self.previewScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.previewScrollArea.setGeometry(QtCore.QRect(30, 270, 991, 281))
        self.previewScrollArea.setWidgetResizable(True)
        self.previewScrollArea.setObjectName("previewScrollArea")
        self.previewScrollAreaWidgetContents = QtWidgets.QWidget()
        self.previewScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 989, 279))
        self.previewScrollAreaWidgetContents.setObjectName("previewScrollAreaWidgetContents")
        self.previewScrollArea.setWidget(self.previewScrollAreaWidgetContents)
        self.previewLabel = QtWidgets.QLabel(self.centralwidget)
        self.previewLabel.setGeometry(QtCore.QRect(30, 240, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.previewLabel.setFont(font)
        self.previewLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(938, 234, 113, 31))
        self.refreshButton.setObjectName("refreshButton")
        self.autoRefreshCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.autoRefreshCheckbox.setGeometry(QtCore.QRect(820, 238, 111, 23))
        self.autoRefreshCheckbox.setObjectName("autoRefreshCheckbox")
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInButton.setGeometry(QtCore.QRect(1026, 270, 25, 25))
        self.zoomInButton.setObjectName("zoomInButton")
        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutButton.setGeometry(QtCore.QRect(1026, 300, 25, 25))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.inputScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.inputScrollArea.setGeometry(QtCore.QRect(110, 70, 911, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputScrollArea.sizePolicy().hasHeightForWidth())
        self.inputScrollArea.setSizePolicy(sizePolicy)
        self.inputScrollArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.inputScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.inputScrollArea.setWidgetResizable(True)
        self.inputScrollArea.setObjectName("inputScrollArea")
        self.inputScrollAreaWidgetContents = QtWidgets.QWidget()
        self.inputScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 909, 139))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputScrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.inputScrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.inputScrollAreaWidgetContents.setObjectName("inputScrollAreaWidgetContents")
        self.inputScrollAreaWidget = QtWidgets.QWidget(self.inputScrollAreaWidgetContents)
        self.inputScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 931, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputScrollAreaWidget.sizePolicy().hasHeightForWidth())
        self.inputScrollAreaWidget.setSizePolicy(sizePolicy)
        self.inputScrollAreaWidget.setStyleSheet("QWidget { background: white }")
        self.inputScrollAreaWidget.setObjectName("inputScrollAreaWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.inputScrollAreaWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1050, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.inputVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.inputVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.inputVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.inputVerticalLayout.setSpacing(0)
        self.inputVerticalLayout.setObjectName("inputVerticalLayout")
        self.measureInputWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureInputWidget.sizePolicy().hasHeightForWidth())
        self.measureInputWidget.setSizePolicy(sizePolicy)
        self.measureInputWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.measureInputWidget.setObjectName("measureInputWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.measureInputWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 911, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.measureInputHLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.measureInputHLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.measureInputHLayout.setContentsMargins(6, 0, 6, 0)
        self.measureInputHLayout.setObjectName("measureInputHLayout")
        self.inputVerticalLayout.addWidget(self.measureInputWidget)
        self.separator_1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.separator_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_1.setObjectName("separator_1")
        self.inputVerticalLayout.addWidget(self.separator_1)
        self.trebleInputWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trebleInputWidget.sizePolicy().hasHeightForWidth())
        self.trebleInputWidget.setSizePolicy(sizePolicy)
        self.trebleInputWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.trebleInputWidget.setObjectName("trebleInputWidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.trebleInputWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1012, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.trebleInputHLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.trebleInputHLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.trebleInputHLayout.setContentsMargins(6, 0, 6, 0)
        self.trebleInputHLayout.setObjectName("trebleInputHLayout")
        self.inputVerticalLayout.addWidget(self.trebleInputWidget)
        self.separator_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.separator_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_2.setObjectName("separator_2")
        self.inputVerticalLayout.addWidget(self.separator_2)
        self.bassInputWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bassInputWidget.sizePolicy().hasHeightForWidth())
        self.bassInputWidget.setSizePolicy(sizePolicy)
        self.bassInputWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bassInputWidget.setObjectName("bassInputWidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.bassInputWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 911, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.bassInputHLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.bassInputHLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.bassInputHLayout.setContentsMargins(6, 0, 6, 0)
        self.bassInputHLayout.setObjectName("bassInputHLayout")
        self.inputVerticalLayout.addWidget(self.bassInputWidget)
        self.inputScrollArea.setWidget(self.inputScrollAreaWidgetContents)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 71, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.labelVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.labelVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.labelVerticalLayout.setObjectName("labelVerticalLayout")
        self.measureLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.measureLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.measureLabel.setObjectName("measureLabel")
        self.labelVerticalLayout.addWidget(self.measureLabel)
        self.trebleLable = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.trebleLable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trebleLable.setObjectName("trebleLable")
        self.labelVerticalLayout.addWidget(self.trebleLable)
        self.bassLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.bassLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bassLabel.setObjectName("bassLabel")
        self.labelVerticalLayout.addWidget(self.bassLabel)
        self.slurButton = QtWidgets.QPushButton(self.centralwidget)
        self.slurButton.setGeometry(QtCore.QRect(610, 20, 89, 31))
        self.slurButton.setCheckable(True)
        self.slurButton.setAutoExclusive(False)
        self.slurButton.setObjectName("slurButton")
        self.unfoldingButton = QtWidgets.QPushButton(self.centralwidget)
        self.unfoldingButton.setGeometry(QtCore.QRect(710, 20, 131, 31))
        self.unfoldingButton.setCheckable(True)
        self.unfoldingButton.setAutoExclusive(False)
        self.unfoldingButton.setObjectName("unfoldingButton")
        self.lineButton = QtWidgets.QPushButton(self.centralwidget)
        self.lineButton.setGeometry(QtCore.QRect(850, 20, 89, 31))
        self.lineButton.setCheckable(True)
        self.lineButton.setAutoExclusive(False)
        self.lineButton.setObjectName("lineButton")
        self.urlinieCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.urlinieCheckbox.setGeometry(QtCore.QRect(950, 20, 71, 31))
        self.urlinieCheckbox.setObjectName("urlinieCheckbox")
        Schenky.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Schenky)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Schenky.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Schenky)
        self.statusbar.setObjectName("statusbar")
        Schenky.setStatusBar(self.statusbar)
        self.propertiesPanel = QtWidgets.QDockWidget(Schenky)
        self.propertiesPanel.setMaximumSize(QtCore.QSize(402, 524287))
        self.propertiesPanel.setStyleSheet("")
        self.propertiesPanel.setFloating(False)
        self.propertiesPanel.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.propertiesPanel.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.propertiesPanel.setObjectName("propertiesPanel")
        self.propertiesPanelContents = QtWidgets.QWidget()
        self.propertiesPanelContents.setObjectName("propertiesPanelContents")
        self.tabWidget = QtWidgets.QTabWidget(self.propertiesPanelContents)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 381, 571))
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.noteTab = QtWidgets.QWidget()
        self.noteTab.setObjectName("noteTab")
        self.notePropertiesTable = QtWidgets.QTableWidget(self.noteTab)
        self.notePropertiesTable.setGeometry(QtCore.QRect(0, 0, 381, 541))
        self.notePropertiesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notePropertiesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.notePropertiesTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.notePropertiesTable.setAlternatingRowColors(True)
        self.notePropertiesTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.notePropertiesTable.setWordWrap(True)
        self.notePropertiesTable.setCornerButtonEnabled(True)
        self.notePropertiesTable.setRowCount(7)
        self.notePropertiesTable.setColumnCount(2)
        self.notePropertiesTable.setObjectName("notePropertiesTable")
        item = QtWidgets.QTableWidgetItem()
        self.notePropertiesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notePropertiesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.notePropertiesTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable)
        self.notePropertiesTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.notePropertiesTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.notePropertiesTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.notePropertiesTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.notePropertiesTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notePropertiesTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notePropertiesTable.setItem(6, 0, item)
        self.notePropertiesTable.horizontalHeader().setDefaultSectionSize(125)
        self.notePropertiesTable.horizontalHeader().setStretchLastSection(True)
        self.notePropertiesTable.verticalHeader().setVisible(False)
        self.notePropertiesTable.verticalHeader().setDefaultSectionSize(25)
        self.tabWidget.addTab(self.noteTab, "")
        self.slursTab = QtWidgets.QWidget()
        self.slursTab.setObjectName("slursTab")
        self.tabWidget.addTab(self.slursTab, "")
        self.unfoldingsTab = QtWidgets.QWidget()
        self.unfoldingsTab.setObjectName("unfoldingsTab")
        self.tabWidget.addTab(self.unfoldingsTab, "")
        self.linesTab = QtWidgets.QWidget()
        self.linesTab.setObjectName("linesTab")
        self.tabWidget.addTab(self.linesTab, "")
        self.propertiesPanel.setWidget(self.propertiesPanelContents)
        Schenky.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.propertiesPanel)
        self.actionNew = QtWidgets.QAction(Schenky)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(Schenky)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Schenky)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(Schenky)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(Schenky)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(Schenky)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(Schenky)
        self.actionPaste.setObjectName("actionPaste")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Schenky)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Schenky)

    def retranslateUi(self, Schenky):
        _translate = QtCore.QCoreApplication.translate
        Schenky.setWindowTitle(_translate("Schenky", "Schenky"))
        self.keyLabel.setText(_translate("Schenky", "Key signature:"))
        self.keySelect.setStatusTip(_translate("Schenky", "Choose a key"))
        self.keySelect.setItemText(0, _translate("Schenky", "C major"))
        self.keySelect.setItemText(1, _translate("Schenky", "G major"))
        self.keySelect.setItemText(2, _translate("Schenky", "D major"))
        self.keySelect.setItemText(3, _translate("Schenky", "A major"))
        self.keySelect.setItemText(4, _translate("Schenky", "E major"))
        self.keySelect.setItemText(5, _translate("Schenky", "B major"))
        self.keySelect.setItemText(6, _translate("Schenky", "F# major"))
        self.keySelect.setItemText(7, _translate("Schenky", "C# major"))
        self.keySelect.setItemText(8, _translate("Schenky", "Cb major"))
        self.keySelect.setItemText(9, _translate("Schenky", "Gb major"))
        self.keySelect.setItemText(10, _translate("Schenky", "Db major"))
        self.keySelect.setItemText(11, _translate("Schenky", "Ab major"))
        self.keySelect.setItemText(12, _translate("Schenky", "Eb major"))
        self.keySelect.setItemText(13, _translate("Schenky", "Bb major"))
        self.keySelect.setItemText(14, _translate("Schenky", "F major"))
        self.keySelect.setItemText(15, _translate("Schenky", "A minor"))
        self.keySelect.setItemText(16, _translate("Schenky", "E minor"))
        self.keySelect.setItemText(17, _translate("Schenky", "B minor"))
        self.keySelect.setItemText(18, _translate("Schenky", "F# minor"))
        self.keySelect.setItemText(19, _translate("Schenky", "C# minor"))
        self.keySelect.setItemText(20, _translate("Schenky", "G# minor"))
        self.keySelect.setItemText(21, _translate("Schenky", "D# minor"))
        self.keySelect.setItemText(22, _translate("Schenky", "A# minor"))
        self.keySelect.setItemText(23, _translate("Schenky", "Ab minor"))
        self.keySelect.setItemText(24, _translate("Schenky", "Eb minor"))
        self.keySelect.setItemText(25, _translate("Schenky", "Bb minor"))
        self.keySelect.setItemText(26, _translate("Schenky", "F minor"))
        self.keySelect.setItemText(27, _translate("Schenky", "C minor"))
        self.keySelect.setItemText(28, _translate("Schenky", "G minor"))
        self.keySelect.setItemText(29, _translate("Schenky", "D minor"))
        self.previewScrollArea.setStatusTip(_translate("Schenky", "Schenkerian graph preview"))
        self.previewLabel.setText(_translate("Schenky", "Preview:"))
        self.refreshButton.setStatusTip(_translate("Schenky", "Refresh Schenkerian graph"))
        self.refreshButton.setText(_translate("Schenky", "Refresh"))
        self.autoRefreshCheckbox.setToolTip(_translate("Schenky", "Uncheck for better performance"))
        self.autoRefreshCheckbox.setStatusTip(_translate("Schenky", "Auto-refresh the Schenkerian graph"))
        self.autoRefreshCheckbox.setText(_translate("Schenky", "Auto-refresh"))
        self.zoomInButton.setStatusTip(_translate("Schenky", "Zoom In"))
        self.zoomInButton.setText(_translate("Schenky", "+"))
        self.zoomOutButton.setStatusTip(_translate("Schenky", "Zoom Out"))
        self.zoomOutButton.setText(_translate("Schenky", "-"))
        self.inputScrollAreaWidget.setStatusTip(_translate("Schenky", "Add/remove note"))
        self.measureLabel.setText(_translate("Schenky", "Measure:"))
        self.trebleLable.setText(_translate("Schenky", "Treble:"))
        self.bassLabel.setText(_translate("Schenky", "Bass:"))
        self.slurButton.setStatusTip(_translate("Schenky", "Select this button then click two notes to form a slur"))
        self.slurButton.setText(_translate("Schenky", "Slur Mode"))
        self.unfoldingButton.setStatusTip(_translate("Schenky", "Select this button then click two notes to form an unfolding"))
        self.unfoldingButton.setText(_translate("Schenky", "Unfolding Mode"))
        self.lineButton.setStatusTip(_translate("Schenky", "Select this button then click a sequence of notes to form a line"))
        self.lineButton.setText(_translate("Schenky", "Line Mode"))
        self.urlinieCheckbox.setText(_translate("Schenky", "Urlinie"))
        self.menuFile.setTitle(_translate("Schenky", "File"))
        self.menuEdit.setTitle(_translate("Schenky", "Edit"))
        self.propertiesPanel.setStatusTip(_translate("Schenky", "Properties panel"))
        self.propertiesPanel.setWindowTitle(_translate("Schenky", "Properties"))
        self.notePropertiesTable.setStatusTip(_translate("Schenky", "Edit note properties"))
        item = self.notePropertiesTable.horizontalHeaderItem(0)
        item.setText(_translate("Schenky", "Property"))
        item = self.notePropertiesTable.horizontalHeaderItem(1)
        item.setText(_translate("Schenky", "Value"))
        __sortingEnabled = self.notePropertiesTable.isSortingEnabled()
        self.notePropertiesTable.setSortingEnabled(False)
        item = self.notePropertiesTable.item(0, 0)
        item.setText(_translate("Schenky", "ID"))
        item = self.notePropertiesTable.item(1, 0)
        item.setText(_translate("Schenky", "Note name"))
        item = self.notePropertiesTable.item(2, 0)
        item.setText(_translate("Schenky", "Accidental"))
        item = self.notePropertiesTable.item(3, 0)
        item.setText(_translate("Schenky", "Register"))
        item = self.notePropertiesTable.item(4, 0)
        item.setText(_translate("Schenky", "Slurs to..."))
        item = self.notePropertiesTable.item(5, 0)
        item.setText(_translate("Schenky", "Unfolds with..."))
        item = self.notePropertiesTable.item(6, 0)
        item.setText(_translate("Schenky", "Part of lines..."))
        self.notePropertiesTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.noteTab), _translate("Schenky", "Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.slursTab), _translate("Schenky", "Slurs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.unfoldingsTab), _translate("Schenky", "Unfoldings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linesTab), _translate("Schenky", "Lines"))
        self.actionNew.setText(_translate("Schenky", "New"))
        self.actionNew.setStatusTip(_translate("Schenky", "Create a new file"))
        self.actionNew.setShortcut(_translate("Schenky", "Ctrl+N"))
        self.actionOpen.setText(_translate("Schenky", "Open"))
        self.actionOpen.setStatusTip(_translate("Schenky", "Open a file"))
        self.actionOpen.setShortcut(_translate("Schenky", "Ctrl+O"))
        self.actionSave.setText(_translate("Schenky", "Save"))
        self.actionSave.setStatusTip(_translate("Schenky", "Save file"))
        self.actionExit.setText(_translate("Schenky", "Exit"))
        self.actionCopy.setText(_translate("Schenky", "Copy"))
        self.actionCopy.setShortcut(_translate("Schenky", "Ctrl+C"))
        self.actionCut.setText(_translate("Schenky", "Cut"))
        self.actionCut.setShortcut(_translate("Schenky", "Ctrl+X"))
        self.actionPaste.setText(_translate("Schenky", "Paste"))
        self.actionPaste.setShortcut(_translate("Schenky", "Ctrl+V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Schenky = QtWidgets.QMainWindow()
    ui = Ui_Schenky()
    ui.setupUi(Schenky)
    Schenky.show()
    sys.exit(app.exec_())
